# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af426173b2391fedce8dc3eb3bf2e91b3312b63641380075cae1ba1b695001d20659420e1021c66663b68622c884e1579f3bb942c5ba3536593a6007d133fefe

test:
  secret_key_base: 0f810928b3b7ea7f866ec5a78425bcda5357284ed36c6583446e76c34aab5849678482bcf6c97b3f356dca341c3bfbf1dd69950757caffd6a13368cecf1b0983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
